### ISSUE TITLE
Were RFC 7540 priority signals ever supposed to be bidirectional?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http2-spec#1000]
Apologies for raising this here and now but here we go.

Based on feedback from our AD and now directorate reviews of draft-ietf-httpbis-priority, it seems that RFC 7540 and 7540bis are ambiguos about whether priority signals are supposed to be sent and processed in the client-to-server only, or whether they can also be in the server-to-client direction. Bob says this question was unanswered in his original review of RFC 7540 - https://lists.w3.org/Archives/Public/ietf-http-wg/2015JanMar/0529.html

The first para of [Section 5.3](https://datatracker.ietf.org/doc/html/rfc7540#section-5.3) says

> A client can assign a priority for a new stream by including
   prioritization information in the HEADERS frame (Section 6.2) that
   opens the stream.  At any other time, the PRIORITY frame
   (Section 6.3) can be used to change the priority of a stream.
   
But beyond that there isn't really anything else. In contrast, server push is clearly server-to-client, there's the requirement

> Thus, servers MUST treat the receipt of a
   PUSH_PROMISE frame as a connection error (Section 5.4.1) of type
   PROTOCOL_ERROR.
   
The reason I'm asking is because we wrote draft-ietf-httpbis-priority assuming that signals were client-to-server only, and that is causing a few sharp edges that are hard to resolve without a conclusive answer. FWIW, I've never heard of active use of signals in the server-to-client direction.

**Comment by Lukasa** [comment]
I think your assessment is right: RFC 7540 allows both peers to send PRIORITY frames and leaves it entirely unspecified what that might mean. Servers reprioritising streams is not terribly useful, so no-one did. There's no contradictions here: RFC 7540 makes it clear that prioritisation is advisory and peers can choose what they do with it, and in all cases clients have effectively chosen to ignore prioritisation signals from servers. I believe this is reasonable.

For my part, I don't see any value in _keeping_ this functionality, not least because it never did anything sensible anyway.

**Comment by LPardue** [comment]
So I think it's fair to say the wire format allows server-to-client priority signals but they, to our collective knowledge, were never applied to anything. RFC 7540 does a poor job of explaining what such signals would apply to, so its little surprise.

7540bis leaves details of applying stream priority to RFC 7540. That seems fine.

So perhaps what we could do is in RFC 7540bis is add some text around https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#section-5.3.1-2 like "priority signals from server to client were supported but implementations did not use this feature".

**Comment by Lukasa** [comment]
I'm not sure we should add any text at all. I don't think we need to list every way in which 7540 priority failed: it did, and we have removed all the relevant text relating to it. It seems a bit strange to try to provide guidance on how to use a feature we're asking implementers not to use.

**Comment by LPardue** [comment]
That's up to you as editors. What I can say though is that this quirk exists and we've had several rounds of review of priorities that asked us to stop casting shade on HTTP/2 so we can't talk about it there. Because you've chosen to eliminate the text about how to act on the signals (deferring back to RFC 7540) then there is no other way to address that quirk, and I'll just have to point people at this issue in future.

**Comment by Lukasa** [comment]
For my part I think it's fine to leave this quirk unaddressed. We don't need to add text to revisions of a spec to address all possible behaviours in no-longer-specified protocol features. In RFC 7540, priority signals from servers to clients were unspecified. In 7540-bis, they're still unspecified, and so are 7540-style priority signals from clients to servers. Arguably we've harmonised things 😉

**Comment by LPardue** [comment]
I can live with this outcome, close at your discretion.

**Comment by martinthomson** [comment]
I share Cory's view.  We're moving on.

There is some cause to talk about the value of server-to-intermediary signals, but I think that the priority draft does that well.  Much better than RFC 7540 did.

**Comment by kazuho** [comment]
I agree to the consensus.

FWIW, it is my understanding that RFC 7540 explicitly _allows_ servers send PRIORITY_UPDATE frames. Quoting from section 5.1:
* _(in reserved (local)), an endpoint MUST NOT send any type of frame other than HEADERS, RST_STREAM, or PRIORITY_
* _In the absence of more specific guidance elsewhere in this document, implementations SHOULD treat the receipt of a frame that is not expressly permitted in the description of a state as a connection error (Section 5.4.1) of type PROTOCOL_ERROR. Note that PRIORITY can be sent and received in any stream state._

To maintain wire compatibility with RFC 7540, the only path forward, as we seem to agree, is to continue allowing servers send PRIORITY frames.
