### ISSUE TITLE
pseudo-header stricter validation

### ISSUE THREAD

**Issue by wtarreau** [httpwg/http2-spec#1015]
Before we definitely forget about it, could we please have a consideration for that one:

   https://github.com/httpwg/http2-spec/pull/936#issuecomment-910260086

There is nothing in H2 that prevents pseudo headers from being abused, and it's suggested that they have to be reassembled to make the whole request line, that is usually parsed later to extract the relevant parts, leading to the trouble reported in the portswigger article. And semantics only apply to the recomposed parts, which is too late.

I would really like that we suggest controls there so that future implementations do not get caught by this uncovered area, and the comment above proposes the minimalist controls that protect against such attacks.

**Comment by mnot** [comment]
Willy, this document is now through IESG evaluation and is about to go to the RFC Editor. Adding substantial new text with requirements would require going back to the working group.

**Comment by martinthomson** [comment]
Sorry for letting that comment pass at the time @wtarreau.  It's a reasonable request, but I don't think that we can go as far as specifying specific validation rules.  URIs are just too complicated for that.

I suggest that we add a special note to [Section 10.3](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#section-10.3) which already talks about how intermediaries might be forced to pass on bad stuff.  See #1017.

**Comment by wtarreau** [comment]
@martinthomson I understand and your approach looks reasonable, many thanks! I've added a tiny comment so that we don't forget to mention ":method" that was also severely abused there, and it's OK for me. @mnot I'm not trying to perform substantial changes but have been trying to reload that one over the last 6 months so that we don't miss it. It has been the main cause of generalized vulnerabilities coming from word-for-word implementation of the spec into code, the least we can do is warn implementers.
