### ISSUE TITLE
Sections 8.5 and 9.1.1 (comment 19)

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#1045]
[Sections 8.5](https://www.rfc-editor.org/authors/rfc9113.html#section-8.5) and 9.1.1:  We quoted "https" where
preceded by "resources".  Please let us know if this is incorrect.

Original:

     CONNECT is primarily
     used with HTTP proxies to establish a TLS session with an origin
     server for the purposes of interacting with https resources.
    ...
     For https resources, connection reuse additionally depends on having
     a certificate that is valid for the host in the URI.

Currently (best viewed in the .html or .pdf output):
 CONNECT is primarily
 used with HTTP proxies to establish a TLS session with an origin
 server for the purposes of interacting with "https" resources.
...
 For "https" resources, connection reuse additionally depends on
 having a certificate that is valid for the host in the URI.

**Comment by martinthomson** [comment]
Folded into #1085.
