### ISSUE TITLE
Sections 9.1.1 and 9.2 (comment 22)

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#1058]
[Sections 9.1.1](https://www.rfc-editor.org/authors/rfc9113.html#section-9.1.1) and 9.2:  "SNI" is not used in [TLS-EXT]
(RFC 6066) or elsewhere in this document.  Also, this abbreviation
wasn't used in [Section 9.1](https://www.rfc-editor.org/authors/rfc9113.html#section-9.1), Paragraph 4.  Is it necessary?

We also see one instance of "SNI" in RFC-to-be 9114; the abbreviation
doesn't appear to serve any specific purpose:
Server Name Indication (SNI; [RFC6066])

Original:

     For
     example, TLS termination might be performed by a middlebox that uses
     the TLS Server Name Indication (SNI) [TLS-EXT] extension to select an
     origin server.
    ...
     The TLS implementation MUST support the Server Name Indication (SNI)
     [TLS-EXT] extension to TLS.

**Comment by Lukasa** [comment]
We can safely remove it.
