### ISSUE TITLE
Sections 10.8 and 10.9 (comment 28)

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#1064]
[Sections 10.8](https://www.rfc-editor.org/authors/rfc9113.html#section-10.8) and 10.9:  Please confirm that these
instances of "value" should not be "values".

Original:

     These
     include the value of settings, the manner in which flow-control
     windows are managed, the way priorities are allocated to streams, the
     timing of reactions to stimulus, and the handling of any features
     that are controlled by settings.
    ...
     Ensuring that processing time is not dependent on the value of
     secrets is the best defense against any form of timing attack.

Possibly:

     These
     include the values of settings, the manner in which flow-control
     windows are managed, the way priorities are allocated to streams, the
     timing of reactions to stimulus, and the handling of any features
     that are controlled by settings.
    ...
     Ensuring that processing time is not dependent on secret values is
     the best defense against any form of timing attack.

**Comment by Lukasa** [comment]
These should both be "values".

**Comment by martinthomson** [comment]
Values is correct in the first case, but the second should be "a value"
by which it means "any value".
