### ISSUE TITLE
Please confirm that the following erratum reports have
been addressed (comment 34)

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#1070]
Please confirm that the following erratum reports have
been addressed:

<https://www.rfc-editor.org/errata/eid4535>
  (updates to Figure 2)
<https://www.rfc-editor.org/errata/eid6309>
  (the "Frames of unknown types are ignored." sentence)
<https://www.rfc-editor.org/errata/eid4925>
  (We could not determine whether or not the listed updates
  were made.)

**Comment by martinthomson** [comment]
Confirmed.  These are in the pre-history of the document.

**Comment by Lukasa** [comment]
I've also double checked: these are all applied.
