### ISSUE TITLE
reason phrase

### ISSUE THREAD

**Issue by reschke** [httpwg/http2-spec#202]
8.1.2.:

"The response status line has been reduced to a single ":status" header field whose value specifies only the numeric response status code. The status text component of the HTTP/1.1 response has been dropped entirely."

Dropping the reason-phrase might break a few edge cases; is this worth it?

Maybe add a separate optional ":reason-phrase" header field?

**Comment by thurt** [comment]
i'm curious what was the logical reason for dropping the reason phrase?

**Comment by mnot** [comment]
The reason phrase -- even in HTTP/1.1 -- isn't guaranteed to be carried end-to-end; implementations can (and do) ignore it and substitute their own values (e.g., 200 is always "OK", no matter what happens on the wire).

Given that, and overhead in carrying the extra bytes, it made sense to drop it from the wire.
