### ISSUE TITLE
Simplify Padding

### ISSUE THREAD

**Issue by jpinner** [httpwg/http2-spec#505]
1) Remove padding from HEADERS, PUSH_PROMISE, and CONTINUATION frames.

Intermediaries are instructed not to remove padding. Padding on these non-flow-controlled frames can block other streams on multiplexed connections (identically to large header blocks). Further, should padding of header blocks truly be necessary, it is more appropriate for this to occur within HPACK.

2) Remove PAD_HIGH.

The reason for not implementing padding as a separate frame is to be able to pad by less the 8-byte frame header that would be required. This can be accomplished with only PAD_LOW and simplifies the processing of a frame.

**Comment by ioquatix** [comment]
It's not clear to me why we don't have padding on CONTINUATION frames. Would you be able to clarify this decision?
