### ISSUE TITLE
opaque

### ISSUE THREAD

**Issue by sprstnd** [httpwg/http2-spec#749]
The term opaque is being used incorrectly within rfc7540.

**Comment by martinthomson** [comment]
You'll need to be more specific than that I'm afraid.

**Comment by emilv** [comment]
The term "opaque" in programming usually means we shouldn't assign any semantic meaning to the data, and so should not try to interpret it. "Opaque data" should be treated in its entirety as a single entity. This is sometimes called a [magic cookie](https://en.wikipedia.org/wiki/Magic_cookie) or [opaque data type](https://en.wikipedia.org/wiki/Opaque_data_type). This is also the meaning of the word in RFC7540.

**Comment by mnot** [comment]
Cleaning up old issues.
