### ISSUE TITLE
Correct handling of HTTP/2 frames with multiple errors

### ISSUE THREAD

**Issue by eggyal** [httpwg/http2-spec#770]
It's not clear to me from RFC 7540 how an endpoint should behave upon receiving a frame that is erroneous in more than one way.

For example, suppose a server receives the following frame when it has stream id 1 in half-closed (remote) state:

```
{
  length = 4
  type = HEADERS
  flags = PRIORITY
  stream id = 1
  E = 0
  stream dependency = 1
}
```

- According to §4.2, the frame "MUST be treated as a connection error" and the server "MUST send an error code of FRAME_SIZE_ERROR" (because the length of 4 "is too small to contain mandatory frame data", namely the weight and header block fragment fields);
- According to §5.1, the server "MUST respond with a stream error (Section 5.4.2) of type STREAM_CLOSED" (because a frame "other than WINDOW_UPDATE, PRIORITY, or RST_STREAM" was received for a stream that is in "half-closed (remote)" state); and
- According to §5.3.1, the server "MUST treat this as a stream error (Section 5.4.2) of type PROTOCOL_ERROR" (because "a stream cannot depend on itself").

That is to say, according to the RFC, the server MUST (at very least) respond to this frame with one GOAWAY frame and two RST_STREAM frames.  However, sending all these frames would violate other requirements:

- According to §5.4.1, "after sending the GOAWAY frame for an error condition, the endpoint MUST close the TCP connection".  This obviously prevents other frames from being sent.
- According to §5.1, sending a RST_STREAM transitions the stream to closed state, in which "an endpoint MUST NOT send frames other than PRIORITY".  This prevents any further RST_STREAM frames from being sent for the same stream.

In this particular case, it seems reasonable to me that the frame size error should halt further processing of the frame such that neither of the stream errors are even detected: after all, an incorrect frame size may indicate corruption (in which case the rest of the frame's data must also be suspect).  But this is neither clear from the spec nor might other cases be so clear cut.

I see three possibilities, with a reasonably strong leaning toward the first:

1. Clarify that further processing of frames SHOULD (or MUST?) be halted upon encountering an error (I suspect this is what most implementations currently do, irrespective that the RFC says they "MUST" behave otherwise?).  But then the order of processing becomes significant: is it right that this should be left as an implementation detail, or should it be specified?  After all, the above frame might trigger a STREAM_CLOSED stream error from one server and a FRAME_SIZE_ERROR connection error from another, with very different consequences: how might these differences impact intermediaries, caching and retries?  Better I think for the order to be specified.

2. Define a precedence to errors, and mandate that that with highest precedence be sent (for example, connection errors might have higher precedence than stream errors).  But then endpoints must continue processing frames they know to be erroneous simply to discover whether any higher precedence errors also exist (at least until an error of the highest possible precedence is encountered).

3. Permit (require?) all errors arising from a single frame to be transmitted irrespective of any other errors the frame may also have triggered.  Again, endpoints would then continue processing frames that they know to be erroneous—but the peer would then be fully informed of all problems in order that it is better able to recover.

**Comment by MikeBishop** [comment]
I think the simplest explanation is that connection errors are those that suggest there's no way to (safely) continue attempting to parse anything.  I suspect most implementations would find that this frame is not long enough to actually be a HEADERS frame and not attempt to parse it as a frame it cannot actually be.

Thus, while a given implementation could possibly discover one of the stream errors first (thereby sending a RST_STREAM), once you discover the connection error, you're sending the GOAWAY and throwing the connection state away.  The logical implementation is likely to find the connection error immediately and not read far enough to find the others.

**Comment by eggyal** [comment]
I agree, but this is not specified.  Is it okay to leave as an implementation detail, even if most implementations will do the "logical thing"?

**Comment by grmocg** [comment]
The question we should ask is: Is there any behavior that would change that
would cause it to not interoperate here?
I suspect that, regardless of how one interprets this, processing must
stop, and the client may or may not receive an error, thanks to the
vagaries of packet-loss.

If this requires any clarification, I'd pick the path of asserting that any
connection error stops any other processing.

**Comment by wtarreau** [comment]
Actually I also found error handling quite tricky to do, especially regarding when and what to send in GOAWAY frames. One really needs to think in terms of error severity to implement a form of funnel so that more severe errors can still be emitted after less serious ones. One example that quickly comes to mind is that we can send a GOAWAY frame to indicate a graceful shutdown of a connection yet this one is not an error and may be followed by other GOAWAY reporting protocol violations.

I also faced an annoying situation related to TCP where you can't send a GOAWAY frame due to a buffer full situation, and closing after this causes a reset to be emitted due to pending incoming data. So we actually have to enter an input drain state in error situations, which further adds to the implementation complexity.

**Comment by martinthomson** [comment]
QUIC has [a set of error handling principles](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-11-2) that I think h2 would benefit from.

**Comment by Lukasa** [comment]
See #819 for some proposed text to address this. We probably need to workshop it a bit.
