### ISSUE TITLE
Update HTML5 reference

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#771]
The current reference is in the WHATWG "infra standard": https://infra.spec.whatwg.org/#tracking-vector

To use this, we need to ask for the "tracking-vector" anchor to be made permanent.

**Comment by martinthomson** [comment]
https://github.com/whatwg/infra/issues/349 filed.  I have changes for a pull request [staged](https://github.com/martinthomson/http2v2/pull/new/tracking-vector-ref).

**Comment by mnot** [comment]
I'm a bit surprised you chose infra; the fingerprinting guidance document in the W3C is much more complete. There are also _tons_ of academic references that have better descriptions; to start, Eckersley's original paper.

**Comment by martinthomson** [comment]
I was looking for a direct replacement, which is what that is.  I can cite https://w3c.github.io/fingerprinting-guidance/ if you think that is better.  Or https://www.w3.org/TR/fingerprinting-guidance/ if that makes more sense.  I never know which is better.

**Comment by mnot** [comment]
Probably the TR - whatever bibxml says, I'd think.

**Comment by martinthomson** [comment]
I'm going to go with something simpler.  RFC 6973 has an adequate definition.
