### ISSUE TITLE
Remove upgrade mechanism

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#772]
This has not been implemented, so can likely go.

See the discussion on https://github.com/martinthomson/http2v2/issues/2 for more context.

**Comment by Lukasa** [comment]
I’m in favour of removing this. It’s clear that the ecosystem has not found a use for it.

**Comment by wtarreau** [comment]
As a co-author of this one, I agree as well. This resulted from a misunderstanding of the use of the preface that everyone happily uses in clear to distinguish between H1 and H2 (and hence serve as a much easier upgrade).

**Comment by mnot** [comment]
Seems to have support; does anyone have an issue with this?

**Comment by ianswett** [comment]
As stated in today's meeting, this sounds good to me, but it's worth posting on the list.
