### ISSUE TITLE
Consider (partial) removal of priority signaling

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#773]
This probably needs a skeleton left over so that we can avoid interoperability problems that might arise from interactions with peers that still have them. There are some MUST-level requirements around parsing that would need to be identified and marked.

See https://github.com/martinthomson/http2v2/issues/3 for more discussion.

**Comment by mnot** [comment]
This needs more discussion if we're going to do it; otherwise we should drop it. One thing to discuss: if we change the ALPN identifier, does this become more practical?

**Comment by martinthomson** [comment]
Changing ALPN makes anything possible.

So here is what I would propose concretely:

1. Cut the section with the detailed explanation and replace it with some explanatory text about the importance of having prioritization in a multiplexed transport (though not necessarily signaling thereof).
2. Explain that this document used to define a priority signaling scheme, but that the one that was defined was unsuccessful.
3. In that section recommend against using the priority signaling scheme from RFC 7540, but explain that other endpoints that you talk to might send these frames.
4. Point to the new signaling system if that is mature enough (and probably even if it is not).
5. Suggest, but not recommend, that servers pay attention to priority signals using these old mechanisms in the absence of other signals.  This might take a little careful wording, but it's probably enough to caution that ignoring signals might degrade performance and some signals might be better than none. Point to RFC 7540 for the details of how the old scheme works.
6. Leave the definition of the frame type intact, but cut the definitions right down to just the necessary pieces sizes, names, and any mandatory processing (error handling, sizes, ranges, the hard stuff).  This should ensure that people are able to do things like generate the right error codes and skip over the HEADERS frame pieces properly.
7. Leave text about when PRIORITY can be sent in the state machine.  This is important for interoperating with endpoints that generate the frame.

**Comment by kazu-yamamoto** [comment]
Do you have any pointers to explain "unsuccessful"?

**Comment by martinthomson** [comment]
This might be a little blunt, but it covers at lot of the reasons: https://datatracker.ietf.org/doc/html/draft-peon-httpbis-h2-priority-one-less-00

**Comment by martinthomson** [comment]
A draft of this is included here: https://github.com/martinthomson/http2v2/compare/main...martinthomson:prioritectomy?expand=1

**Comment by kazu-yamamoto** [comment]
@martinthomson Thanks.

**Comment by mnot** [comment]
I don't think this is in the scope we agreed to, which means we'll need a specific consensus call about this if you want to pursue it.

**Comment by martinthomson** [comment]
I guess I should have spent more of my vacation time double-checking your list then.  I think that this is worth doing, and the discussion on the list so far seems to support that view, so I hope that a formal ask is not too much to ask of the working group.

**Comment by mnot** [comment]
I remember people being against it, so it definitely would need discussion. I'd suggest doing so on-list. We're likely to have an interim in the new year, which might be useful if it's contentious.

**Comment by Lukasa** [comment]
It seems like draft-ietf-httpbis-priority-03 deprecates the original priority scheme. At least, that's the language it wants to use. It seems like we should at the very least consider updating the language in the document to note that the scheme is deprecated and to direct users to draft-ietf-httpbis-priority. I'd also like to save some bytes and remove the text discussing how the scheme works and direct users to RFC 7540 but I'm open to being persuaded on that point.

**Comment by martinthomson** [comment]
Discussed this at the 2021-02 interim and we'll verify on list.  People have committed to reviewing the proposed changes.

We do want to reference draft-ietf-httpbis-priority.  My current sense is that we'll be finished both at around the same time, so I am inclined to add the reference and consider taking it out if things slip rather than be scared of that possible eventuality.
