### ISSUE TITLE
Improve resource exhaustion attack text

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#775]
The spec includes language on this, but it turned out that many implementations failed to properly safeguard themselves. Clearer descriptions of problems based on this experience would be good.

**Comment by Lukasa** [comment]
I don’t think it hurts to tighten the text up here and add more examples, at least so new implementations are better able to learn from past mistakes. However, we should probably keep in mind that this cannot possibly be an exhaustive list of exhaustion attacks.

**Comment by martinthomson** [comment]
This is the Netflix write-up, which might be a good reference: https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md

I can only imagine citing a markdown file on GitHub will raise eyebrows, but it's not a bad summary of issues.
