### ISSUE TITLE
Reserve some codepoints for greasing

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#776]
This probably is just frames and settings.  We'll have to make it clear that greased frames in particular aren't necessarily safe to send based on deployment experience.  See also [draft-bishop-httpbis-grease](https://mikebishop.github.io/http-misc-extensions/draft-bishop-httpbis-grease.html).

**Comment by wtarreau** [comment]
At the same time, having a section speaking about greasing and encouraging it will definitely help. We could for example mention that any undocumented code point is only relevant when it appears in the context of a negociated support, must be silently ignored outside of this, and that implementations must be prepared to receiving them. For example we could imagine that an agent periodically sends timestamp frames anywhere in communications (streams or connections) and that some implementations might use them and others must drop them.

The only risk is to start to see parallel protocol variations being developed with no negotiation and with implicitly assumed support for some undocumented frame numbers, just like many HTTP header fields became de-facto standard (e.g: x-forwarded-for).

Maybe we should encourage implementations to recognize undocumented frames as greased ones, and add their own greasing on top of them by, for example, just changing the frame type before passing it on. This would make it harder for rogue implementations to rely on their own hard-coded variations.

**Comment by mnot** [comment]
This was discussed at the interim and there seemed to be support for adding grease where possible to H2. I don't think we need to go into the fine details of the greasing points / mechanisms, just have a general intent documented.

**Comment by Lukasa** [comment]
I suspect it's going to be hard to do this without a new ALPN.
