### ISSUE TITLE
Clarify prohibition on use of pseudo-fields relative to extension model

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#778]
RFC 8441 did a thing with settings that allowed it to violate a MUST-level requirement that prohibited use of pseudo-fields. This is OK (because extensions were expressly permitted to do that), but some people are uncomfortable with that.

**Comment by Lukasa** [comment]
I don’t know if we need to loosen the prohibition per se? It seems like we could simply add explanatory language around the MUST NOT to explicitly remind the reader that, per section whatever, negotiated extensions are entitled to change protocol semantics including all of the above MUST/MUST NOTs.

**Comment by martinthomson** [comment]
See also https://www.rfc-editor.org/errata/eid6309

**Comment by martinthomson** [comment]
I wrote a little on this: https://github.com/martinthomson/http2v2/pull/18/files

**Comment by mnot** [comment]
I think this is more "clarify how the extension model interacts with the pseudo-header requirement." If that's all it is, I think it's editorial; otherwise it needs more discussion.

**Comment by martinthomson** [comment]
Based on the above text, that seems right

**Comment by martinthomson** [comment]
Fixed in #796.
