### ISSUE TITLE
Update field terminology

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#779]
The update to core specs uses "fields" generically. If we reference that, then it will get really confusing if we keep saying "HEADERS" or "header fields". We might even consider changing the name of the frame.

See https://github.com/martinthomson/http2v2/issues/9 for more discussion.

**Comment by Lukasa** [comment]
I’m opposed to changing the name of the frame, but otherwise consistency is nice.

**Comment by martinthomson** [comment]
I think that we worked something out.  We can refine over time.
