### ISSUE TITLE
Design for 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#781]
0-RTT is newer than h2. As it stands, when 0-RTT is used, the default settings apply because the server doesn't have any chance to send SETTINGS. That's decidedly suboptimal.

See https://github.com/martinthomson/http2v2/issues/11 for more discussion.

**Comment by wtarreau** [comment]
Actually this could be a reason for rethinking what settings need to be updatable afterwards based on the server's indications. Being faster for most requests on most 0-RTT connections is important, and if on 1/100 of the requests we need to wait for a round trip it's already a nice win. Typically stuff like HPACK encoding can't be changed with 0-RTT support in mind unless a new ALPN identifier is used. But if its only suboptimal for initial requests and that future SETTINGS frames can suggest a change, that could be OK. We could for example imagine that some SETTINGS could be changed from 0 to 1 anywhere on the connection but not the other way around, then start with suboptimal settings for 0-RTT, which would still be good enough.

We could also imagine being a bit more aggressive on certain settings, like we did with the early-data draft, and have the other side gracefully reject what couldn't be handled if this happens.

**Comment by mnot** [comment]
It seems like we need more information here -- in particular a concrete proposal. A bis effort isn't conducive to exploration of new mechanisms.

**Comment by wtarreau** [comment]
I think the goal is not to explore new mechanisms but rather to retrofit some of the parts of RFC8470 related to H2 if deemed necessary.

**Comment by martinthomson** [comment]
I think that this would be relatively simple.  A setting that says "you can rely on these parameters for the next connection" in place of defaults.  And some accompanying rules about what that means for each setting.  For example, the stream limit would apply to the number of streams that can be opened in 0-RTT.  

For the most part, this would be a simple flag on each setting saying whether it should be saved or ignored.  There could be cases where saved/ignored is not sufficiently precise, so something would need to be worked out for that, if it is even possible at all.

**Comment by mnot** [comment]
Discussed in Feb 2021 interim; close with no action.
