### ISSUE TITLE
Update the HPACK static table

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#788]
@LPardue suggests:

The HPACK static table is a bit old. For QPACK we did some analysis and came up with a "new" table, which is probably quite old now itself.

Because the tables are different, they probably consume code size in implementations that provide H2 and H3 (unless people are being clever). Alignment of the tables might reduce overhead.

I'm not going to push hard for doing this work. But it is worth asking the question now and answering it,

Some discussion at https://github.com/martinthomson/http2v2/issues/19.

**Comment by Lukasa** [comment]
As noted at the interim, I’m favour of letting RFC 7541 sit, unmodified, forever. It works. It isn’t perfect, but it works fine. Certainly I don’t want to move forward with updating the table unless we can find compelling data that we see meaningful improvements in doing so.

Irregardless we certainly can’t do this without doing #787.

**Comment by wtarreau** [comment]
Maybe this will change the day we support an improvement/replacement of HPACK as a negociable option. We'd possibly not help much but cause quite some interoperability issues by trying to address such now small issues after shipping. On-wire coding and protocol points must be well thought before a release and not change outside of a versionned update.

**Comment by wtarreau** [comment]
By the way, we won't save code size by replacing HPACK's table because all interoperable implementations will need to keep the old one forever. So actually we'll inflate all implementations by supporting a new one. Better think about an hpack re-encoding or replacement if we want to go through the hassle of dealing with an alternate form.

**Comment by MikeBishop** [comment]
When we have a mechanism that guarantees the presence of SETTINGS before any application data (including 0-RTT), we could reasonably approach this generally.  If we change the ALPN, we might be able to include this as one of the changes that ALPN token implies.  I'm not really gung-ho about making the change in an existing protocol.

**Comment by LPardue** [comment]
I'm agreeing with all the well articulated points on this issue.

**Comment by mnot** [comment]
Feeling here seems to be to NOT update the HPACK static table; if anyone feels strongly otherwise please articulate why.

**Comment by mnot** [comment]
Discussed at Feb 2021 interim; no (will confirm on list).
