### ISSUE TITLE
Consider guidance for new field design wrt compression

### ISSUE THREAD

**Issue by LPardue** [httpwg/http2-spec#790]
This request is motivated by reading RFC 7540 and remembering there's a section all about cookie crumbling.

Is there an opportunity to borrow some of the words from https://www.mnot.net/blog/2018/11/27/header_compression?

**Comment by mnot** [comment]
@mnot to try to condense into something appropriate and then we'll figure out where it might live.

**Comment by mnot** [comment]
Upon reflection, I don't think it's a good idea to put advice for new headers into a specific version of the protocol -- it's not an appropriate place. The cookie crumbing text in h2 is a one-off hack to accommodate a specific situation; I don't think we're contemplating any more of that.

So from my perspective this can be closed without action.

**Comment by martinthomson** [comment]
That there is excellent rationale.  Unless @LPardue objects, I'm happy to close this as a BCP-56 or HTTP-core type of problem.

**Comment by LPardue** [comment]
No objection, let's close.
