### ISSUE TITLE
The requirement to use SNI is not possible always

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#792]
SNI contains a domain name.  Clients connecting to an host in order to make requests for a URL with an IP address authority don't include SNI.  We addressed this better in HTTP/3.

> If the server is identified by a DNS name, clients MUST send the Server Name Indication (SNI; [RFC6066]) TLS extension unless an alternative mechanism to indicate the target host is used.

-- https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-3.2-2

I believe that in practice the requirement is being ignored.  Aligning the spec with reality seems best.

**Comment by martinthomson** [comment]
This proposal uses the QUIC text almost verbatim: https://github.com/martinthomson/http2v2/compare/main...martinthomson:sni-maybe?expand=1

Note that this text comes with two exclusions, which might not be immediately obvious:

1. if the authority is not a domain name, there is no signaling requirement; if you use NetBIOS for name resolution, then we don't mandate anything
2. you don't have to use SNI if you have something better; [ECH](https://tools.ietf.org/html/draft-ietf-tls-esni) is one possibility, but this is deliberately non-specific

**Comment by Lukasa** [comment]
Is it worth providing a non-exhaustive list of examples to help clarify?
