### ISSUE TITLE
ENABLE_PUSH from clients

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#793]
The definition of ENABLE_PUSH implies that it can be set to 0 by a server, but the effect of that is meaningless as it results in treating PUSH_PROMISE as an error.  PUSH_PROMISE can't be sent by a client.

Should we update the definition?

**Comment by Lukasa** [comment]
I don't think it's a good idea to start forbidding ENABLE_PUSH = 0 from servers. It's clearly acceptable from the perspective of the RFC, and while it's a silly waste of bytes it doesn't introduce any protocol ambiguity.

I do think we should clean up the text in § 6.5.2, which currently reads:

> The initial value is 1, which indicates that server push is permitted.  Any value other than 0 or 1 MUST be treated as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

However, Section 8.2 implies the default value for servers is 0:

> Clients MUST reject any attempt to change the SETTINGS_ENABLE_PUSH setting to a value other than 0 by treating the message as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

Arguably these two sections should be reconciled. In principle we could simply say that the value of ENABLE_PUSH has no effect for servers, as the protocol forbids servers from pushing _anyway_, and remove the requirement that clients error.

**Comment by martinthomson** [comment]
I think that you mean clients are forbidden from pushing, but otherwise I would agree.

The initial value for ENABLE_PUSH is defined as 1, which muddies things further.  I think that we can change the definition to say that the setting has no effect when sent by a server and drop the connection error requirement.

**Comment by Lukasa** [comment]
Would we leave the connection error as an option?

**Comment by martinthomson** [comment]
I'm inclined to remove it as being inconsistent with reality.  Though we might have to note that some implementations might do that (because they haven't updated) and so advise strongly against servers sending any value for this setting.

**Comment by Lukasa** [comment]
Is it inconsistent with reality? Presumably some implementations actually do police the MUST here.

**Comment by martinthomson** [comment]
Two things are in tension:

1. policing probably happens in the sense that if a server sends ENABLE_PUSH with any value (especially 1) a client might choke on it
2. the initial value is 1, so those clients should probably choke on a connection preface from the server as well

Removing the requirement that ENABLE_PUSH result in an error avoids the second, but you need to keep a recommendation not to send it or you hit the first.

**Comment by Lukasa** [comment]
I suspect most implementations treat initial values somewhat specially, and while they enforce that they cannot _receive_ a value of 1 from a server, they don’t prevent the server’s setting value having the value of 1.

**Comment by Lukasa** [comment]
This might be one worth circulating with the WG tbh, if only to get a sense of what existing clients actually do. We can also investigate putting together a test suite.
