### ISSUE TITLE
Malformed requests might have been processed

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#794]
The language [here](https://martinthomson.github.io/http2v2/draft-thomson-httpbis-http2bis.html#section-8.1.2.6-3) doesn't properly acknowledge the possibility that some processing might have been performed before an error is detected.  This could use some tweaking.

**Comment by martinthomson** [comment]
Proposal here: https://github.com/martinthomson/http2v2/compare/main...martinthomson:malformed-partial?expand=1

**Comment by Lukasa** [comment]
Seems like a reasonable change.
