### ISSUE TITLE
Connection headers and proxies

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#804]
We have generation rules
> An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed (Section 8.1.2.6).

And we have forwarding rules:
> This means that an intermediary transforming an HTTP/1.x message to HTTP/2 will need to remove any header fields nominated by the Connection header field, along with the Connection header field itself.  Such intermediaries SHOULD also remove other connection-specific header fields, such as Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade, even if they are not nominated by the Connection header field.

In https://github.com/quicwg/base-drafts/pull/4747 for HTTP/3, we are discussing a requirement to remove Transfer-Encoding.  But the "will need to" for the proxy is what seems most strange.  Should this be a MUST instead?

**Comment by mnot** [comment]
The forwarding rules are now subsumed by HTTP-core, i think; you could get by with a reference to [them](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.connection).

**Comment by Lukasa** [comment]
Given the reference to HTTP-core it seems clear that “will need to” should be MUST.

I’m less confident about just x-refing to HTTP-core: HTTP-core tells you to take the Connection field off, so I guess we can X-ref to HTTP-core for removal and then note that intermediaries need to remember that they may not add connection-specific fields to the H2 side of the connection. That should likely be clear enough?

Something like:

> An intermediary transforming an HTTP/1.x message to HTTP/2 will need to remove connection-specific header fields as discussed in [HTTP-core § 7.6.1], or their messages will be treated by other HTTP/2 endpoints as malformed (Section 8.1.2.6).

**Comment by martinthomson** [comment]
That text sounds great.
