### ISSUE TITLE
A wide diagram might be made narrower

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#810]
.../draft-ietf-httpbis-http2bis.xml(311): Warning: Artwork too wide, reducing indentation from 3 to 1

Might be worth trying to fix.

**Comment by Lukasa** [comment]
I think that diagram is this one:

```
        <artwork type="message/http; msgtype=&quot;request&quot;"><![CDATA[
  GET / HTTP/1.1
  Host: server.example.com
  Connection: Upgrade, HTTP2-Settings
  Upgrade: h2c
  HTTP2-Settings: <base64url encoding of HTTP/2 SETTINGS frame payload>

]]></artwork>
```

Might be a pain to rewrite that one to be smaller. Careful wordsmithing?

**Comment by Lukasa** [comment]
I think that has to be the one. It's 72 characters wide at its widest. The next-widest artwork in the RFC is 67 characters, so if we can save 5 characters we'd be fine.

**Comment by reschke** [comment]
Just say something like:

  HTTP2-Settings: <encoded-settings>

and then in the prose say that "encoded-settings" is "base64url encoding of HTTP/2 SETTINGS frame payload"
