### ISSUE TITLE
Any appropriate error code, including generic ones

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#824]
QUIC includes the following statement:

>  In particular, an endpoint MAY use any applicable error code when it detects an error condition; a generic error code (such as PROTOCOL_VIOLATION or INTERNAL_ERROR) can always be used in place of specific error codes.

I like this.  (No accident.  I wrote it.)

Should HTTP/2 include a similar statement?  We have PROTOCOL_ERROR, which has a definition compatible with this statement, so I guess we're already there on as far as allowing a generic code goes.  Any sense in saying it explicitly?

**Comment by Lukasa** [comment]
Yeah, I think this is sensible text to include.
