### ISSUE TITLE
"Parameters" in IANA registries

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#829]
From IANA:

> In recent years we've suggested omitting the word "Parameters" when creating a set of registries, but because the name of the HTTP/2 group uses it, we'll leave it in place unless you prefer otherwise.

As we have the patient open already, it might be OK to change the registry name to follow modern conventions.

**Comment by Lukasa** [comment]
To clarify, IANA would like us to delete the word "Parameters" from the following text?

> These new registries appear in the new "Hypertext
>  Transfer Protocol version 2 (HTTP/2) Parameters" section.
