### ISSUE TITLE
HTTP2-Settings Header Field Registration needs update

### ISSUE THREAD

**Issue by reschke** [httpwg/http2-spec#843]
new registry for fields; see <https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.name.registration>

**Comment by martinthomson** [comment]
@reschke, #820 removed upgrade and changed the registration of this header field to:

> This section marks the `HTTP2-Settings` header field registered in Section 11.5 of [RFC7540] as obsoleted.

Is that OK?  Or would you prefer a complete registration update, as in:

Field Name: HTTP2-Settings
Status: Standard
Ref.: Section 11.5 of RFC 7540
Comments: This field is obsoleted (this document).

**Comment by reschke** [comment]
That should be fine.
