### ISSUE TITLE
Is Content-Length acceptable on CONNECT request?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http2-spec#849]
Up-to-date HTTP core specs say in https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.9.3.6.p.12

> A server MUST NOT send any Transfer-Encoding or Content-Length header fields in a 2xx (Successful) response to CONNECT. A client MUST ignore any Content-Length or Transfer-Encoding header fields received in a successful response to CONNECT.
> 
> A CONNECT request message does not have content. The interpretation of and allowability of data sent after the header section of the CONNECT request message is specific to the version of HTTP in use.

But https://datatracker.ietf.org/doc/html/rfc7540#section-8.3 makes it difficult to see if Content-Length is allowed on request.

It's clear that RFC7540 considers CONNECT requests to have no content. And it's clear that for normal request that if the sum of DATA frames don't match the sum Content-Length then its an error. But it is unclear if the server should quickly reject CONNECT requests that contain "Content-Length: N" (for N > 0), or how they should deal with "Content-Length: 0".

**Comment by Lukasa** [comment]
I don't think we need to make any changes here.

As you quote, CONNECT requests are defined to not have content. This means that they're covered by Semantics § 8.6 (https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.8.6) which reads:

> A user agent should not send a Content-Length header field when the request message does not contain content and the method semantics do not anticipate such data.

No behaviour is specified for a peer that receives such a message, but one assumes that it has the same rough behaviour as, say, sending a Content-Length header field on GET: the semantics are unspecified and so not interoperable. You get what you get. Essentially, implementations are free to do whatever they want when they receive the Content-Length header field on a CONNECT request: they may apply the H2's strict Content-Length policing semantics (in which case any non-zero value should fail), or they may error immediately, or they may ignore the value.

In this instance I don't think there is any value in H2 specifying any additional behaviour above-and-beyond what semantics requires, as the fundamental problem is common across all HTTP messaging formats.

**Comment by LPardue** [comment]
I agree with your points, let's close this.
