### ISSUE TITLE
Revise acknowledgments

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#862]
I don't know what the convention is here, but the acknowledgments seem a little off.  For instance, we acknowledge people for mechanisms that were removed in this revision.

We might be able to remove these entirely; we could simplify (which would avoid problems like the above); or we might just mark these as applying to RFC 7540.  Ideas sought.

**Comment by wtarreau** [comment]
Or maybe just change this to "the participants of the IETF HTTP Working Group" and be done with it, since overall it's the reality, especially for 7540 where lots of discussion happened on the list and it's even possible that a number of participants were never acknowledged.
