### ISSUE TITLE
Minimum value setting mechanism of HTTP2.0 Window and Window_update

### ISSUE THREAD

**Issue by Maisy-ML** [httpwg/http2-spec#863]
RFC 7540 just Specifies the maximum value of Window and the Window  Size Increment, But there is no obvious rule about minimum values.  In the current network, there is no standard minimum setting, which  leads to the inconsistency of message processing between  communication parties, may led to the situation that the  message will be determined as an attack by the recipient, actually  frequent window_UPDATE frames can result in a denial of service.
we  proposed the minimum value setting mechanism of HTTP2.0   Window and Window_update, and a window_update frame sending  mechanism.

**Comment by martinthomson** [comment]
Thanks for raising the issue @Maisy-ML.

The current draft describes small updates as a possible attack in [Section 10.5](https://httpwg.org/http2-spec/draft-ietf-httpbis-http2bis.html#section-10.5-4.1.2.1).  What else do you think we need to say on the subject?

I'm not sure that it will be possible to set a minimum for the size of updates.  Even the smallest increment might be justified under some conditions.

**Comment by Maisy-ML** [comment]
Hi martin, I have reviewed section 10.5, NFLX-2019-002 already contains the CVEs related to DoS, I think there is one more case can be added: Window_update frame can also be abused with small window size increment, may even appear window is updated very samll at a time, not only does it consume link resources and processing resources, When both of them are less than some value, it can also lead to misjudgment of active defense mechanisms.

**Comment by Maisy-ML** [comment]
I have a question,  what cases will there be a small update, what is the range of updates for the smallest increment?

**Comment by martinthomson** [comment]
I don't think that we have specific advice on the minimum size of an update, nor do I think that is appropriate as it will depend on the structure of implementations.  As noted, we only talk about the need to recognize the potential for multiple small updates to cause DoS.  However, small updates are valid in some circumstances.

We discussed this at the last interim and the working group agreed that no change to the document was necessary.  As always, if you think that a specific change would improve the document, proposing a change using a pull request is preferred.
