### ISSUE TITLE
Target URIs

### ISSUE THREAD

**Issue by mnot** [httpwg/http2-spec#867]
The `Request Pseudo-Header Fields` section talks about how to generate the various pseudo-header fields from a message, but not not how to create a message from the abstract constructs in HTTP semantics, such as the target URI.

This includes security considerations around trusting the contents of `:scheme`.

I'm happy to do a PR for this.

Also, this is a weird paragraph:

> HTTP/2 uses the "http" and "https" URI schemes defined in <xref target="HTTP" section="4.2"/>. HTTP/2 shares the same default port numbers: 80 for "http" URIs and 443 for "https" URIs.  As a result, implementations processing requests for target resource URIs like <tt>http://example.org/foo</tt> or <tt>https://example.com/bar</tt> are required to first discover whether the upstream server (the immediate peer to which the client wishes to establish a connection) supports HTTP/2.

"HTTP/2 shares the same default port numbers" implies that it could choose to do otherwise; while that might have been an open question pre-core, I think this needs to be re-worded. Likewise, "requests for target resource URIs" is odd; is this meant to be "requests with target URIs"?

**Comment by martinthomson** [comment]
Yeah, most of this is just OLD.  For instance, the "discovery" aspect really only relates to the need to use ALPN, but we have a better nomenclature now.

If you are happy to do a PR, I'm more than happy to review rather than write.
