### ISSUE TITLE
Unpromised Push

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#878]
As a corollary to https://github.com/quicwg/base-drafts/issues/4930, I cannot find anything in RFC 7540 that explicitly prohibits the server sending a response on a stream that hasn't been promised.  The closest is the state machine, where a push stream is supposed to go from idle to reserved to half-closed.  The statement that it can go from idle to open upon sending a HEADERS frame is clearly oriented at the client, but is endpoint-agnostic:  `Sending or receiving a HEADERS frame causes the stream to become "open".`

**Comment by Lukasa** [comment]
Hmm, I haven't found much explicit either. § 5.1.1 of the editors draft says:

> A HEADERS frame will transition the client-initiated stream identified by the stream identifier in the frame header from "idle" to "open". A PUSH_PROMISE frame will transition the server-initiated stream identified by the "Promised Stream ID" field in the frame payload from "idle" to "reserved".

This _implies_ that only clients can use HEADERS frames, but isn't exactly emphatic.

However, I think the actual prohibition comes from the fact that we import the HTTP semantics nearly wholesale in § 8, with several bits of text in § 8.1 implying that servers can't do this:

> A client sends an HTTP request on a new stream, using a previously unused stream identifier (Section 5.1.1). A server sends an HTTP response on the same stream as the request.

> An HTTP request/response exchange fully consumes a single stream. A request starts with the HEADERS frame that puts the stream into an "open" state.

With all of that said, I don't think it would be a bad idea to add text that explicitly prohibits servers from sending unsolicited responses.

**Comment by MikeBishop** [comment]
Yes, I think this is solved simply by saying that if the client receives any frame on an idle server-initiated stream (i.e. one that hasn't yet been reserved), it's an error.  In the process, the statement about HEADERS in the stream state machine should be made client-specific.

**Comment by MikeBishop** [comment]
In reading the doc, I note that 5.1 is similarly vague about clients sending / servers receiving PUSH_PROMISE.  That's addressed elsewhere more explicitly, since PUSH_PROMISE is only sent by servers, but I wonder if we should use the same language around them in this section that we are for HEADERS in #879.
