### ISSUE TITLE
http-scheme without out-of-band

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#881]
Should there be a reference to RFC 8164 in the discussion about using HTTP/2 with "http://" URLs?  We have defined a way to do that which doesn't rely on out-of-band knowledge, after all.

**Comment by martinthomson** [comment]
I think that the experiment has concluded in the negative, so I don't really want to reference that.  We already mention (in general) that HTTP is able to carry URLs for other schemes; so that spec can join all the other non-https schemes.

**Comment by martinthomson** [comment]
I propose that we leave this unaddressed.  @Lukasa, WDYT?

**Comment by Lukasa** [comment]
Agreed
