### ISSUE TITLE
nit: is h2c spec'd or not

### ISSUE THREAD

**Issue by LPardue** [httpwg/http2-spec#892]
Maybe a hangover from trying to tear up the photos of the "http" URI and upgrade dance. But this seems to read oddly. 

On one hand:

> This usage was never widely deployed, and is no longer specified in this document.

on the other:

> Negotiating "h2" or "h2c" implies the use of the transport, security, framing, and message semantics described in this document.

I don't have a solid suggestion to improve things.

**Comment by martinthomson** [comment]
How about we just remove "h2c" from the latter statement.

**Comment by martinthomson** [comment]
OK, that isn't going to fly.  I just tried it.  Pulling that string is unwise.

We agreed to keep "prior knowledge" in the document, and the "h2c" ALPN token is part of that.  The "h2c" upgrade token has been removed already.  (Too subtle?  Probably.)
