### ISSUE TITLE
Does the HEADERS Padding field have the same requirements as DATA?

### ISSUE THREAD

**Issue by LPardue** [httpwg/http2-spec#896]
I just realised RFC 7540 was always this way, but it doesn't seem right to me.

The DATA frame definition includes normative requirements on sender and receiver using the `Padding` field. I presume the HEADERS frame `padding` is supposed the treat padding the same but it isn't written down.

edit: plus PUSH_PROMISE

**Comment by LPardue** [comment]
Ah, it's stated in a separate paragraph at the end of each frame definition section. That's annoying but I guess its fine.

**Comment by Lukasa** [comment]
Yeah, so the short answer there is that they behave differently in some ways (at least with respect to flow control). If you think there’s a better way to structure the section I think you’re welcome to take a crack at it.

**Comment by LPardue** [comment]
I didn't actually make the leap the flow control, that makes me more inclined to avoid the cross reference to DATA frames. I made #898 to just make everything explicit at the cost of a few more lines of text.
