### ISSUE TITLE
"from another HTTP version"

### ISSUE THREAD

**Issue by martinthomson** [httpwg/http2-spec#913]
@wtarreau points to some stuff from RFC 7540 that might be cleaned up in terms of "control data" and so forth.

In addition in this paragraph at several places it's mentioned "from
another HTTP version", but as soon as you have to deal with multiple
versions on each side of an intermediary, you don't deal with versions,
in fact you're using an "HTTP" internal representation which relies on
semantics and in this case it becomes strange to make an exception for
the case where the other side is using exactly the same version. Given
that we're now having a version-agnostic spec for the semantics, I
would suggest that we avoid speaking about versions in the H2 spec and
instead strictly rely on semantics. This is even more important when
the text mentions what to do to convert towards other versions, as this
job usually is in fact to be done on the other side (from the semantic
layer to the other version), and is highly likely to be missed.

For example, it's mentioned:

> For reference, an HTTP/1.1 Section 3.2 of request target [HTTP11] in
> authority-form always includes authority, a request target in absolute-form
> includes authority if the target URI includes authority, and request
> targets in origin- or asterisk-form do not include authority.

Just having this starts to preclude rules on how to parse an HTTP/1
request that dangerously overlap with [messaging].

**Comment by martinthomson** [comment]
... @wtarreau continues

I could suggest to simplify this part like this (don't take it word
for word, I'm trying to illustrate):

> An intermediary that forwards a request to HTTP/2 MUST translate
> any authority information from the request into an :authority
> pseudo-header field. If the original request does not contain
> authority information, the intermediary MUST NOT add an :authority
> pseudo-header field. Please note that the presence of a Host header
> field does not necessarily imply presence of an authority; refer
> to [semantics] for details.

**Comment by MikeBishop** [comment]
@martinthomson, I don't believe #907 attempts to address this issue.
