### ISSUE TITLE
Stream State Machine and Extension Frames

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#915]
As discussed in [Erratum 6309](https://www.rfc-editor.org/errata/eid6309), the current language of 5.1 prohibits *all* frames on closed streams other than the ones indicated.  It is not clear whether the requirement in Section 5.5 constitutes "more specific guidance."  My suggestion in the erratum was to scope "any frame" to "any frame defined in this document" where we might allow an extension frame to appear, since that was the minimal change to the RFC 7540 text, but the editors might choose a broader rewording.

**Comment by martinthomson** [comment]
So the text already says: "Frames of unknown types are ignored." right next to the guidance you refer to.  Maybe we just need to be more direct about this.

**Comment by wtarreau** [comment]
Be careful Martin, you removed the sentence "Frames of unknown types are ignored" so I think we're losing one piece of information when looking at the patch. I should re-read it withiin its context to make sure we don't miss anything, but I preferred to warn.

**Comment by martinthomson** [comment]
@wtarreau, yes, that was a deliberate change.  I replaced that text with a complete paragraph and a reference to the extensibility section, which already covers the rules for unknown frames clearly: "Implementations MUST discard frames that have unknown or unsupported types."
