### ISSUE TITLE
Frame "contains" an END_STREAM flag

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#916]
(Warning, I may have reached peak pedantry.)

In Section 5.1, there are two references to frames which "contain" an END_STREAM flag. All HEADERS, CONTINUATION, and DATA frames contain this flag, which might be set or not.  Most other references in the document are to the flag being set, which is more precise.

There are also two references to frames "bearing" END_STREAM, which could be taken either way.

**Comment by martinthomson** [comment]
If you care enough to write the issue, maybe you also care enough to offer a pull request.
