### ISSUE TITLE
Inconsistent capitalization of "Flag(s)"

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#917]
In various cases, the term "Flag" is capitalized, e.g.:

>When set, the PRIORITY Flag indicates that the Exclusive, Stream Dependency, and Weight fields are present.

In others, it's not:

>A HEADERS frame without the END_HEADERS flag set....

I can't identify a consistent rationale for when it is capitalized and when not.

**Comment by martinthomson** [comment]
I don't know if it is just the limitations of my search, but I just searched for `/[A-Z]+ flag/` and `/[A-Z]+ Flag/` and I found just one of the former.  That is the one case you found.

As in QUIC, I think we can refer to the fields in the frame layouts in the Title Case form in which they are presented.  That is also the minimal change.
