### ISSUE TITLE
Are transfer codings allowed for HTTP/2?

### ISSUE THREAD

**Issue by MikeBishop** [httpwg/http2-spec#938]
HTTP/2 prohibits `chunked` Transfer-Encoding, but doesn't actually prohibit other values:

> The chunked transfer encoding defined in Section 7.1 of [HTTP11] cannot be used in HTTP/2.

HTTP/3 broadened this language to cover all transfer codings:

> Transfer codings (see Section 6.1 of [HTTP11]) are not defined for HTTP/3; the Transfer-Encoding header field MUST NOT be used.

Should H2bis follow suit?

**Comment by martinthomson** [comment]
Can you take this to the list Mike?  It seems like the only sensible answer, but I'd like to double-check.

**Comment by mnot** [comment]
In my mind, I was relying on Section 8.2.2:

> An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields; any message containing connection-specific header fields MUST be treated as malformed

However, that probably isn't linked well enough to the [current text in core](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#field.connection). Unfortunately, there isn't a term we can just lift out; perhaps something like this:

> An endpoint MUST NOT generate an HTTP/2 message containing hop-by-hop header fields, including those listed in Section 7.6.1 of [HTTP]; a received message containing such fields MUST be treated as malformed

**Comment by martinthomson** [comment]
On review with fully context, the text that Mike cites is fine.  It's an informational note.  Mark's note here about the linkage to -semantics is good though.  I will float this on the list to see if I messed up (again).
